[package]
name = "mch"
version = "0.1.0"
authors = ["Florian Barth <florianbarth@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
approx = "0.4.0"
glpk-sys = "0.2.0"
